
-- *--------------------------------------------------------------------------------
-- CREATE SNOWFLAKE USERS and OBJECTS
 
--   Run this scription to create the object in the account you will be performance testing
--   - Creates a user called loadtest_sfc
--   - Creates a warehouse used by Tableau
--   - A materialized table from account_usage.query_history that can be used with Tableau
--   - A view that can be used with Tableau (slower, but you don't need to update after runs)
 
--   Author:   Chris Richardson
--   Updated:  
--   15 JAN 2020 - crichardson - initial
--   14 FEB 2020 - crichardson - Added SQL for permissions on SNOWFLAKE and SMAPLE_DATA shares
 
-- --------------------------------------------------------------------------------*/
 
-- ---- CREATE USER
-- --- This is the user that will run the tests 

 
USE ROLE SECURITYADMIN;
 
CREATE or REPLACE USER loadtest_sfc
PASSWORD = 'Snow2020#'
DEFAULT_ROLE = PERSHINGX_ADMIN
MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE PERSHINGX_ADMIN TO USER loadtest_sfc;
 
-- We don't want this user to hit the results cache.
ALTER USER loadtest_sfc  SET USE_CACHED_RESULT=FALSE;
 
-- Grant access to the SNOWFLAKE share for statistitcs 
USE ROLE ACCOUNTADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE PERSHINGX_ADMIN;

-- Grant access to SNOWFLAKE_SAMPLE_DATA share for running TPC-DS
CREATE DATABASE SNOWFLAKE_SAMPLE_DATA FROM SHARE SFC_SAMPLES.SNOWFLAKE_SAMPLE_DATA;
GRANT IMPORTED PRIVILEGES ON DATABASE snowflake_sample_data TO ROLE PERSHINGX_ADMIN;
 
 
---- CREATE OBJECTS
USE ROLE PERSHINGX_ADMIN;
 
-- This is a WH for Tableau
use role sysadmin;

CREATE WAREHOUSE IF NOT EXISTS TABLEAU_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
WAREHOUSE_TYPE = 'STANDARD'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 1
INITIALLY_SUSPENDED = TRUE
SCALING_POLICY = 'STANDARD';

use role securityadmin;

grant ownership on warehouse TABLEAU_WH to role PERSHINGX_ADMIN; 
 
use role pershingx_admin;
create schema JMETER;

-- Example TABLE for Tableau workbook
CREATE or REPLACE TABLE PERSHINGX.JMETER.LOADTEST_SFC AS (
SELECT
QUERY_ID,
QUERY_TEXT,
DATABASE_NAME,
SCHEMA_NAME,
QUERY_TYPE,
SESSION_ID,
USER_NAME,
ROLE_NAME,
WAREHOUSE_NAME,
WAREHOUSE_SIZE,
WAREHOUSE_TYPE,
CLUSTER_NUMBER,
QUERY_TAG,
EXECUTION_STATUS,
ERROR_CODE,
ERROR_MESSAGE,
START_TIME,
END_TIME,
TOTAL_ELAPSED_TIME,
BYTES_SCANNED,
ROWS_PRODUCED,
COMPILATION_TIME,
EXECUTION_TIME,
QUEUED_PROVISIONING_TIME,
QUEUED_REPAIR_TIME,
QUEUED_OVERLOAD_TIME,
TRANSACTION_BLOCKED_TIME,
OUTBOUND_DATA_TRANSFER_CLOUD,
OUTBOUND_DATA_TRANSFER_REGION,
OUTBOUND_DATA_TRANSFER_BYTES,
INBOUND_DATA_TRANSFER_CLOUD,
INBOUND_DATA_TRANSFER_REGION,
INBOUND_DATA_TRANSFER_BYTES
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
where 1=1
AND USER_NAME='LOADTEST_SFC'
--AND START_TIME > dateadd('days',-1,current_timestamp())
AND START_TIME > dateadd('hours',-1,current_timestamp())
-- AND START_TIME>'2022-06-16 09:00:00'
AND QUERY_TYPE='SELECT'
AND LENGTH(QUERY_TAG) >1
)
;
 
 
-- Example view for LoadTest workbook (This can be slow)
CREATE or REPLACE VIEW PERSHINGX.JMETER.VW_LOADTEST_SFC AS (
SELECT
QUERY_ID,
QUERY_TEXT,
DATABASE_NAME,
SCHEMA_NAME,
QUERY_TYPE,
SESSION_ID,
USER_NAME,
ROLE_NAME,
WAREHOUSE_NAME,
WAREHOUSE_SIZE,
WAREHOUSE_TYPE,
CLUSTER_NUMBER,
QUERY_TAG,
EXECUTION_STATUS,
ERROR_CODE,
ERROR_MESSAGE,
START_TIME,
END_TIME,
TOTAL_ELAPSED_TIME,
BYTES_SCANNED,
ROWS_PRODUCED,
COMPILATION_TIME,
EXECUTION_TIME,
QUEUED_PROVISIONING_TIME,
QUEUED_REPAIR_TIME,
QUEUED_OVERLOAD_TIME,
TRANSACTION_BLOCKED_TIME,
OUTBOUND_DATA_TRANSFER_CLOUD,
OUTBOUND_DATA_TRANSFER_REGION,
OUTBOUND_DATA_TRANSFER_BYTES,
INBOUND_DATA_TRANSFER_CLOUD,
INBOUND_DATA_TRANSFER_REGION,
INBOUND_DATA_TRANSFER_BYTES
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
where 1=1
AND USER_NAME='LOADTEST_SFC'
--AND START_TIME > dateadd('days',-1,current_timestamp())
AND START_TIME > dateadd('hours',-1,current_timestamp())
AND QUERY_TYPE='SELECT'
AND LENGTH(QUERY_TAG) >1
)
;